location ~* ^/wp-content/uploads/.*$ {
    autoindex off;
    location ~* \.php$ {
        deny all;
    }
    location ~* \.(pl|py|jsp|asp|sh|cgi|exe|bat|cmd)$ {
        deny all;
    }
    location ~* /\.(ht|env|git) {
        deny all;
    }
}

location ~* ^/wp-content/wc-uploads/.*$ {
    autoindex off;
    location ~* \.php$ {
        deny all;
    }
}

location = /wp-content/uploads/ { return 403; }
location = /wp-content/uploads  { return 403; }

location ~* ^/wp-content/.*\.(sql|bak|log|ini|conf|config)$ {
    deny all;
}
location ~* \.(bak|backup|old|orig|save|swp|sql|log|ini|conf|config)$ {
    deny all;
}
location ~* /\.ht {
    deny all;
}
