services:
  wireguard:
    image: linuxserver/wireguard:latest
    container_name: wireguard
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Bogota
      - SERVERURL=${WG_SERVERURL}
      - SERVERPORT=${WG_SERVERPORT}
      - PEERS=${WG_PEERS:-2}
      - PEERDNS=1.1.1.1,8.8.8.8
      - PERSISTENTKEEPALIVE_PEERS=all
      - INTERNAL_SUBNET=10.13.13.0
      - ALLOWEDIPS=0.0.0.0/0
      - LOG_CONFS=true
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    restart: unless-stopped
