[PHP]
memory_limit = 1024M
max_execution_time = 300
max_input_time = 300
max_input_vars = 10000
default_socket_timeout = 300
post_max_size = 256M
upload_max_filesize = 256M
file_uploads = On
max_file_uploads = 50

display_errors = Off
display_startup_errors = Off
log_errors = On
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
error_log = /var/log/php/php84-error.log

date.timezone = America/Bogota

session.cookie_httponly = 1
session.cookie_secure = 1
session.use_strict_mode = 1
session.gc_maxlifetime = 1440
session.save_path = "/tmp"

expose_php = Off
allow_url_fopen = On
allow_url_include = Off

sendmail_path = /bin/true

disable_functions = passthru,system,shell_exec,pcntl_exec,pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait

realpath_cache_size = 4096K
realpath_cache_ttl = 600
